project_id = "fmifbxrqbwkyjgkgceyh"

[functions.send-charges]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.sign-contract]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.email-events]
verify_jwt = false

[functions.email-cron]
verify_jwt = false
