/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as ParaProprietariosRouteImport } from './routes/para-proprietarios'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnunciosRouteImport } from './routes/anuncios'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssinarTokenRouteImport } from './routes/assinar.$token'
import { Route as AnunciosIdRouteImport } from './routes/anuncios.$id'
import { Route as AuthenticatedVistoriaRouteImport } from './routes/_authenticated/vistoria'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedMeusAnunciosRouteImport } from './routes/_authenticated/meus-anuncios'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as ApiPublicSignContractRouteImport } from './routes/api/public/sign-contract'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaProprietariosRoute = ParaProprietariosRouteImport.update({
  id: '/para-proprietarios',
  path: '/para-proprietarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciosRoute = AnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarTokenRoute = AssinarTokenRouteImport.update({
  id: '/assinar/$token',
  path: '/assinar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciosIdRoute = AnunciosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnunciosRoute,
} as any)
const AuthenticatedVistoriaRoute = AuthenticatedVistoriaRouteImport.update({
  id: '/vistoria',
  path: '/vistoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusAnunciosRoute =
  AuthenticatedMeusAnunciosRouteImport.update({
    id: '/meus-anuncios',
    path: '/meus-anuncios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSignContractRoute = ApiPublicSignContractRouteImport.update({
  id: '/api/public/sign-contract',
  path: '/api/public/sign-contract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRouteWithChildren
  '/auth': typeof AuthRoute
  '/para-proprietarios': typeof ParaProprietariosRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/meus-anuncios': typeof AuthenticatedMeusAnunciosRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/vistoria': typeof AuthenticatedVistoriaRoute
  '/anuncios/$id': typeof AnunciosIdRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/sign-contract': typeof ApiPublicSignContractRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRouteWithChildren
  '/auth': typeof AuthRoute
  '/para-proprietarios': typeof ParaProprietariosRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/meus-anuncios': typeof AuthenticatedMeusAnunciosRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/vistoria': typeof AuthenticatedVistoriaRoute
  '/anuncios/$id': typeof AnunciosIdRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/sign-contract': typeof ApiPublicSignContractRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/anuncios': typeof AnunciosRouteWithChildren
  '/auth': typeof AuthRoute
  '/para-proprietarios': typeof ParaProprietariosRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/meus-anuncios': typeof AuthenticatedMeusAnunciosRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRoute
  '/_authenticated/vistoria': typeof AuthenticatedVistoriaRoute
  '/anuncios/$id': typeof AnunciosIdRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/sign-contract': typeof ApiPublicSignContractRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anuncios'
    | '/auth'
    | '/para-proprietarios'
    | '/planos'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/configuracoes'
    | '/contracts'
    | '/dashboard'
    | '/expenses'
    | '/meus-anuncios'
    | '/payments'
    | '/properties'
    | '/relatorios'
    | '/tenants'
    | '/vistoria'
    | '/anuncios/$id'
    | '/assinar/$token'
    | '/api/public/asaas-webhook'
    | '/api/public/sign-contract'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncios'
    | '/auth'
    | '/para-proprietarios'
    | '/planos'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/configuracoes'
    | '/contracts'
    | '/dashboard'
    | '/expenses'
    | '/meus-anuncios'
    | '/payments'
    | '/properties'
    | '/relatorios'
    | '/tenants'
    | '/vistoria'
    | '/anuncios/$id'
    | '/assinar/$token'
    | '/api/public/asaas-webhook'
    | '/api/public/sign-contract'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anuncios'
    | '/auth'
    | '/para-proprietarios'
    | '/planos'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contracts'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/meus-anuncios'
    | '/_authenticated/payments'
    | '/_authenticated/properties'
    | '/_authenticated/relatorios'
    | '/_authenticated/tenants'
    | '/_authenticated/vistoria'
    | '/anuncios/$id'
    | '/assinar/$token'
    | '/api/public/asaas-webhook'
    | '/api/public/sign-contract'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnunciosRoute: typeof AnunciosRouteWithChildren
  AuthRoute: typeof AuthRoute
  ParaProprietariosRoute: typeof ParaProprietariosRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  AssinarTokenRoute: typeof AssinarTokenRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiPublicSignContractRoute: typeof ApiPublicSignContractRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-proprietarios': {
      id: '/para-proprietarios'
      path: '/para-proprietarios'
      fullPath: '/para-proprietarios'
      preLoaderRoute: typeof ParaProprietariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncios': {
      id: '/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof AnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar/$token': {
      id: '/assinar/$token'
      path: '/assinar/$token'
      fullPath: '/assinar/$token'
      preLoaderRoute: typeof AssinarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncios/$id': {
      id: '/anuncios/$id'
      path: '/$id'
      fullPath: '/anuncios/$id'
      preLoaderRoute: typeof AnunciosIdRouteImport
      parentRoute: typeof AnunciosRoute
    }
    '/_authenticated/vistoria': {
      id: '/_authenticated/vistoria'
      path: '/vistoria'
      fullPath: '/vistoria'
      preLoaderRoute: typeof AuthenticatedVistoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-anuncios': {
      id: '/_authenticated/meus-anuncios'
      path: '/meus-anuncios'
      fullPath: '/meus-anuncios'
      preLoaderRoute: typeof AuthenticatedMeusAnunciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sign-contract': {
      id: '/api/public/sign-contract'
      path: '/api/public/sign-contract'
      fullPath: '/api/public/sign-contract'
      preLoaderRoute: typeof ApiPublicSignContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedMeusAnunciosRoute: typeof AuthenticatedMeusAnunciosRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRoute
  AuthenticatedVistoriaRoute: typeof AuthenticatedVistoriaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedMeusAnunciosRoute: AuthenticatedMeusAnunciosRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRoute,
  AuthenticatedVistoriaRoute: AuthenticatedVistoriaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AnunciosRouteChildren {
  AnunciosIdRoute: typeof AnunciosIdRoute
}

const AnunciosRouteChildren: AnunciosRouteChildren = {
  AnunciosIdRoute: AnunciosIdRoute,
}

const AnunciosRouteWithChildren = AnunciosRoute._addFileChildren(
  AnunciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnunciosRoute: AnunciosRouteWithChildren,
  AuthRoute: AuthRoute,
  ParaProprietariosRoute: ParaProprietariosRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  AssinarTokenRoute: AssinarTokenRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiPublicSignContractRoute: ApiPublicSignContractRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
