// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmifbxrqbwkyjgkgceyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtaWZieHJxYndreWpna2djZXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIzOTc1MDYsImV4cCI6MjA5Nzk3MzUwNn0.oEQEgLah6d8WL3vnAqxNxsHR-NtLK0Ncow0GHdbwstI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});